#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

mkdir -p dist/artifacts
tar cvJf dist/artifacts/rancher-cloud-controller-manager${SUFFIX}.tar.xz -C ./bin .
